name: Cron Test

on:
  schedule:
    - cron: "*/10 * * * *" # кожні 10 хвилин (для тесту)
  workflow_dispatch: # кнопка "Run workflow"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Cron працює 🚀"